In [2]:
import importlib
import matplotlib.pyplot as plt
import numpy as np
from gal_goku import summary_stats
importlib.reload(summary_stats)

data_dir = '/home/qezlou/HD2/HETDEX/cosmo/data/xi_on_grid/'
xi = summary_stats.Xi(data_dir, fid='HF', narrow=False, logging_level='INFO')

halo_tools not available, won't be able to use propagator.
summary_stats | 01/01/2026 03:08:58 PM | Rank 0 | INFO  |  mass_bins = [11.  11.1 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3]
summary_stats | 01/01/2026 03:08:58 PM | Rank 0 | INFO  |  mass_bins = [11.  11.1 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2 12.3]


In [3]:
xi.xi.shape

(21, 105, 50)

In [4]:
xi.get_data()

summary_stats | 01/01/2026 03:09:02 PM | Rank 0 | INFO  |  Found 0.1 % of xi(r,n1,n2) is nan
summary_stats | 01/01/2026 03:09:02 PM | Rank 0 | INFO  |  Found 0.1 % of xi(r,n1,n2) is nan
log_corr.shape: (21, 2730), rbins.size: 26, mass_pairs.shape: (105, 2)


/home/qezlou/HD2/HETDEX/cosmo/pack_dev/private-gal-emu/src/gal_goku/gal_goku/summary_stats.py:1137: RuntimeWarning: invalid value encountered in log10
  log_corr = np.log10(self.xi[:,:,ind_r]).squeeze()


(array([[12.30000019, 12.30000019,  0.21268578],
        [12.30000019, 12.30000019,  0.26343238],
        [12.30000019, 12.30000019,  0.32628708],
        ...,
        [11.        , 11.        , 41.98406441],
        [11.        , 11.        , 53.52949432],
        [11.        , 11.        , 60.52631579]]),
 array([[ 2.0305717,  2.532688 ,  2.2527475, ..., -1.3307202, -1.5895734,
         -1.7248826],
        [ 1.6993587,  1.4899606,  1.5681317, ..., -2.1813354, -2.5636573,
         -2.7651474],
        [ 1.9243883,  1.9468842,  1.8892525, ..., -1.7347403, -2.103262 ,
         -2.3026721],
        ...,
        [ 5.002238 , -1.       , -1.       , ..., -1.2014408, -1.4646242,
         -1.5845994],
        [ 1.1221594,  1.1356813,  1.1213508, ..., -2.1057553, -2.4534328,
         -2.6384284],
        [ 1.3925467,  1.3916857,  1.5001415, ..., -1.9366736, -2.3036287,
         -2.5082214]], dtype=float32),
 array([[      0.,       0.,       0., ...,       0.,       0.,       0.],
        [ 